name: Precommit

on:
  push:
    branches: 
      - trunk
  pull_request:
    branches: 
      - trunk

jobs:
  build:
    strategy:
      matrix:
        compiler:
          - gcc
          - clang
        optimization_level: 
          - -O0
          - -O3
        sanitizers:
          - ''
          - 'address,leak'

    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install build-essential
          sudo apt install gcc
          sudo apt install clang clang-format clang-tidy
          sudo apt install bear

      - name: Build
        run: |
          if [[ -z "${{ matrix.sanitizers }}" ]]; then
              SAN=""
          else
              SAN="-fsanitize=${{ matrix.sanitizers }}"
          fi
          bear -- make compile \
            COMPILER=${{ matrix.compiler }} \
            OPTIMIZATION_LEVEL=${{ matrix.optimization_level }}\
            SANITIZERS="$SAN"

      - name: Test
        run: |
          for i in {1..8}; do
            echo "|- Running #$i..."
            ./build/bin/app
          done

      - name: Check Format
        run: make check-format

      - name: Check Style
        run: make check-style
